### ISSUE TITLE
Determine if rulesets should be using this for their testing

### ISSUE THREAD

**Issue by alexeagle** [p0deje/setup-bazel#1]
As part of moving this repo to bazel-contrib, I'm curious if we should consider changing https://github.com/bazel-contrib/rules-template/blob/main/.github/workflows/ci.yaml to use this. I wrote that reusable action that it references but it's not sophisticated about the caching.

**Comment by alexeagle** [comment]
I'm starting on this here: https://github.com/bazel-contrib/.github/pull/13

**Comment by p0deje** [comment]
Yes, we can absolutely use the action, though I wonder if rulesets want caches enabled at all - it seems to me that a cacheless setup is preferred, at least that's what we do in rules_ruby.

**Comment by alexeagle** [comment]
What are the pros and cons of using this for rulesets? How do you feel they are different from other projects?

**Comment by p0deje** [comment]
The main reason I'm not using the caches in rulesets is that I want to make sure the toolchains can be installed from scratch. This way I could catch regressions in repository rules that for example download and compile Ruby.

**Comment by alexeagle** [comment]
It's useful just for the bazelrc to set enable_bzlmod, and I think the repository cache as well since it contains content-addressed bytes and only accessed when the user supplies an integrity hash. So, I think the answer is yes :)
