### ISSUE TITLE
Does "simple configuration" do anything?

### ISSUE THREAD

**Issue by alexeagle** [p0deje/setup-bazel#2]
The README has a first example:

> Simple configuration
> - uses: p0deje/setup-bazel@0.6.0

Isn't this a no-op? Empty bazelisk version means to use the one installed by github, and all the caches are false by default. If someone pastes this, aren't they misusing this action? If so I don't think we should document a wrong way to use it.

**Comment by p0deje** [comment]
Yes, it's pretty much a no-op when used without parameters. The only thing that's configured is a a proper output base on Windows:

https://github.com/p0deje/setup-bazel/blob/0565e39cc057545da6e6974739d945c6ef55cd55/index.js#L104-L107

What do you think should be a default behavior? Caches turned on?

**Comment by alexeagle** [comment]
Well as a start, I think just removing this option from the README is a good start. Most folks will use a copy-paste example if there's a convenient one.
